export const APP_CONFIGURATION_DETAILS = "APP_CONFIGURATION_DETAILS";
export const APP_CONFIGURATION_DETAILS_SUCCESS =
  "APP_CONFIGURATION_DETAILS_SUCCESS";
export const APP_CONFIGURATION_DETAILS_FAILED =
  "APP_CONFIGURATION_DETAILS_FAILED";
export const FETCHING_APP_CONFIG = "FETCHING_APP_CONFIG";
export const FETCH_APP_CONFIG_SUCCESS = "FETCH_APP_CONFIG_SUCCESS";
export const FETCH_APP_CONFIG_FAILED = "FETCH_APP_CONFIG_FAILED";
