export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const UPDATING_TRIP_OBJECT = "UPDATING_TRIP_OBJECT";
export const UPDATING_TRIP_OBJECT_SUCCESS = "UPDATING_TRIP_OBJECT_SUCCESS";
export const UPDATING_TRIP_OBJECT_FAILED = "UPDATING_TRIP_OBJECT_FAILED";
