export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";
export const FETCHING_USER = "FETCHING_USER";

export const FETCHING_ALL_USERS = "FETCHING_ALL_USERS";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILED = "FETCH_ALL_USERS_FAILED";

export const FETCH_USER_STATS_CHARTS_SUCCESS =
  "FETCH_USER_STATS_CHARTS_SUCCESS";
export const FETCH_USER_STATS_CHARTS_FAILED = "FETCH_USER_STATS_CHARTS_FAILED";
export const FETCHING_USER_STATS_CHARTS = "FETCHING_USER_STATS_CHARTS";

export const CREATE_NEW_USER_REQ = "CREATE_NEW_USER_REQ";
export const CREATE_NEW_USER_REQ_SUCCESS = "CREATE_NEW_USER_REQ_SUCCESS";
export const CREATE_NEW_USER_REQ_FAILED = "CREATE_NEW_USER_REQ_FAILED";

export const UPDATE_USER_LIST_OBJECT = "UPDATE_USER_LIST_OBJECT";

export const CHANGE_PASSWORD_REQ = "CHANGE_PASSWORD_REQ";
export const CHANGE_PASSWORD_REQ_SUCCESS = "CHANGE_PASSWORD_REQ_SUCCESS";
export const CHANGE_PASSWORD_REQ_FAILED = "CHANGE_PASSWORD_REQ_FAILED";
