export const SERVER_CONFIGURATION_DETAILS = "SERVER_CONFIGURATION_DETAILS";
export const SERVER_CONFIGURATION_DETAILS_SUCCESS =
  "SERVER_CONFIGURATION_DETAILS_SUCCESS";
export const SERVER_CONFIGURATION_DETAILS_FAILED =
  "SERVER_CONFIGURATION_DETAILS_FAILED";
export const FETCHING_SERVER_CONFIG = "FETCHING_SERVER_CONFIG";
export const FETCH_SERVER_CONFIG_SUCCESS = "FETCH_SERVER_CONFIG_SUCCESS";
export const FETCH_SERVER_CONFIG_FAILED = "FETCH_SERVER_CONFIG_FAILED";
