// constant for trips
export const FETCHING_USER_TRIP_DETAILS = "FETCHING_USER_TRIP_DETAILS";
export const FETCH_USER_TRIP_DETAIL_SUCCESS = "FETCH_USER_TRIP_DETAIL_SUCCESS";
export const FETCH_USER_TRIP_DETAIL_FAILED = "FETCH_USER_TRIP_DETAIL_FAILED";
// constant for user details
export const FETCHING_USER_DETAILS = "FETCHING_USER_DETAILS";
export const FETCH_USER_DETAIL_SUCCESS = "FETCH_USER_DETAIL_SUCCESS";
export const FETCH_USER_DETAIL_FAILED = "FETCH_USER_DETAIL_FAILED";
// constant for active driver details
export const FETCHING_ACTIVEDRIVERS_DETAILS = "FETCHING_ACTIVEDRIVERS_DETAILS";
export const FETCH_ACTIVEDRIVERS_DETAILS_SUCCESS =
  "FETCH_ACTIVEDRIVERS_DETAILS_SUCCESS";
export const FETCH_ACTIVEDRIVERS_DETAILS_FAILED =
  "FETCH_ACTIVEDRIVERS_DETAILS_FAILED";

// constant for active customer details
export const FETCHING_ACTIVECUSTOMERS_DETAILS =
  "FETCHING_ACTIVECUSTOMERS_DETAILS";
export const FETCH_ACTIVECUSTOMERS_DETAILS_SUCCESS =
  "FETCH_ACTIVECUSTOMERS_DETAILS_SUCCESS";
export const FETCH_ACTIVECUSTOMERS_DETAILS_FAILED =
  "FETCH_ACTIVECUSTOMERS_DETAILS_FAILED";

// constant for active customer details
export const FETCHING_APPROVE_PENDING_USERS = "FETCHING_APPROVE_PENDING_USERS";
export const FETCH_APPROVE_PENDING_USERS_SUCCESS =
  "FETCH_APPROVE_PENDING_USERS_SUCCESS";
export const FETCH_APPROVE_PENDING_USERS_FAILED =
  "FETCH_APPROVE_PENDING_USERS_FAILED";

// constant to approve user
export const APPROVING_SELECTED_USER = "APPROVING_SELECTED_USER";
export const APPROVING_SELECTED_USER_SUCCESS =
  "APPROVING_SELECTED_USER_SUCCESS";
export const APPROVING_SELECTED_USER_FAILED = "APPROVING_SELECTED_USER_FAILED";

// constant to rejectUser
export const REJECTING_SELECTED_USER = "REJECTING_SELECTED_USER";
export const REJECTING_SELECTED_USER_SUCCESS =
  "REJECTING_SELECTED_USER_SUCCESS";
export const REJECTING_SELECTED_USER_FAILED = "REJECTING_SELECTED_USER_FAILED";
