export const FETCH_TRIPS_SUCCESS = "FETCH_TRIPS_SUCCESS";
export const FETCH_TRIPS_FAILED = "FETCH_TRIPS_FAILED";
export const FETCHING_TRIPS = "FETCHING_TRIPS";

export const FETCH_REVENUE_GRAPH_DATA = "FETCH_REVENUE_GRAPH_DATA";
export const FETCH_REVENUE_GRAPH_DATA_FAILED =
  "FETCH_REVENUE_GRAPH_DATA_FAILED";
export const FETCH_REVENUE_GRAPH_DATA_SUCCESS =
  "FETCH_REVENUE_GRAPH_DATA_SUCCESS";

export const CREATING_NEW_TRIP = "CREATING_NEW_TRIP";
export const CREATING_NEW_TRIP_SUCCESS = "CREATING_NEW_TRIP_SUCCESS";
export const CREATING_NEW_TRIP_FAILED = "CREATING_NEW_TRIP_FAILED";

export const FETCHING_ONGOINGTRIP_DRIVER_RIDER_DETAILS =
  "FETCHING_ONGOINGTRIP_DRIVER_RIDER_DETAILS";
export const FETCH_ONGOINGTRIP_DRIVER_RIDER_DETAILS_SUCCESS =
  "FETCH_ONGOINGTRIP_DRIVER_RIDER_DETAILS_SUCCESS";
export const FETCH_ONGOINGTRIP_DRIVER_RIDER_DETAILS_FAILED =
  "FETCH_ONGOINGTRIP_DRIVER_RIDER_DETAILS_FAILED";

export const FETCHING_RECENTREVIEWEDTRIP_DRIVER_RIDER_DETAILS =
  "FETCHING_RECENTREVIEWEDTRIP_DRIVER_RIDER_DETAILS";
export const FETCH_RECENTREVIEWEDTRIP_DRIVER_RIDER_DETAILS_SUCCESS =
  "FETCH_RECENTREVIEWEDTRIP_DRIVER_RIDER_DETAILS_SUCCESS";
export const FETCH_RECENTREVIEWEDTRIP_DRIVER_RIDER_DETAILS_FAILED =
  "FETCH_RECENTREVIEWEDTRIP_DRIVER_RIDER_DETAILS_FAILED";

export const UPDATE_TRIP_LIST_OBJECT = "UPDATE_TRIP_LIST_OBJECT";
