export const OPEN_USER_DETAILS_MODAL = "OPEN_USER_DETAILS_MODAL";
export const CLOSE_USER_DETAILS_MODAL = "CLOSE_USER_DETAILS_MODAL";

export const UPDATING_USER_DETAILS_OBJECT = "UPDATING_USER_DETAILS_OBJECT";
export const UPDATING_USER_DETAILS_OBJECT_SUCCESS =
  "UPDATING_USER_DETAILS_OBJECT_SUCCESS";
export const UPDATING_USER_DETAILS_OBJECT_FAILED =
  "UPDATING_USER_DETAILS_OBJECT_FAILED";
