export const FETCHING_TRIP_DETAILS = "FETCHING_TRIP_DETAILS";
export const FETCH_TRIP_DETAIL_SUCCESS = "FETCH_TRIP_DETAIL_SUCCESS";
export const FETCH_TRIP_DETAIL_FAILED = "FETCH_TRIP_DETAIL_FAILED";

export const FETCHING_SPECIFIC_USER_TRIPS = "FETCHING_SPECIFIC_USER_TRIPS";
export const FETCH_SPECIFIC_USER_TRIPS_SUCCESS =
  "FETCH_SPECIFIC_USER_TRIPS_SUCCESS";
export const FETCH_SPECIFIC_USER_TRIPS_FAILED =
  "FETCH_SPECIFIC_USER_TRIPS_FAILED";
